# Generated by Django 3.2.3 on 2021-06-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(),
        ),
    ]
